= Sobre o Autor

O Venerável Ajahn Sumedho foi o primeiro monge ocidental a ser ordenado
na Tradição Tailandesa da Floresta, tradição esta que faz parte do
Budismo Theravada, a escola do Budismo que predomina no Sri Lanka e no
Sudeste Asiático. Neste último século a clareza e simplicidade dos
ensinamentos budistas têm sido bem recebidos no Ocidente como fonte de
paz e de compreensão, que faz frente aos rigorosos testes da nossa
presente geração.

Ajahn Sumedho nasceu em Seattle, Washington, em 1934. Cresceu no seio de
uma família anglicana juntamente com a sua irmã mais velha. Aos dezoito
anos de idade serviu na Marinha dos Estados Unidos, durante quatro anos,
o que incluiu o período da Guerra da Coreia. Após o serviço militar
completou um bacharelato em Estudos do Extremo Oriente, em 1973,
graduando-se com um mestrado em Estudos do Sudoeste Asiático, na
Universidade da Califórnia, Berkeley. Serviu no Corpo de Paz como
professor de Inglês de 1974 a 1976, trabalhando após esse período como
assistente social na Cruz Vermelha.

Desiludido e insatisfeito com o dogmatismo da religião ocidental, decide
em 1966 viajar até à Tailândia para praticar meditação em Wat Mahathat,
Bangkok. Pouco depois em 1967 decide ordenar-se como monge em Nong Khai,
Nordeste da Tailândia. Após um ano de prática solitária sentiu
necessidade de um professor que pudesse guiá-lo mais profundamente. Foi
então que ocorreu um afortunado encontro com um monge visitante que o
levou à província de Ubon para conhecer o Venerável Ajahn Chah, no
mosteiro Wat Nong Pah Pong. Tornou-se então, oficialmente um discípulo
de Ajahn Chah e permaneceu sob a sua tutela durante dez anos. Os
mosteiros de Ajahn Chah eram conceituados pela sua austeridade e
abordagem simples e directa da prática do Dhamma. Em 1975 Ajahn Sumedho
estabeleceu Wat Pah Nanachat, Mosteiro Internacional da Floresta, com o
objectivo de treinar os ocidentais interessados em seguir a vida
monástica.

Em 1977, a convite do _English Sangha Trust_, acompanhou Ajahn Chah a
Inglaterra, residindo temporariamente na Hampstead Vihāra, em Londres,
com outros três monges. O objectivo do _English Sangha Trust_ era
estabelecer as condições apropriadas para o treino de monges no
Ocidente. Este objectivo foi estabelecido em 1979 com a aquisição de uma
casa em ruínas em West Sussex, posteriormente conhecido como Chithurst
Buddhist Monastery ou _Cittaviveka_.

Com a inauguração deste mosteiro o Sangha começou a crescer rapidamente,
iniciando também o treino para mulheres como monjas budistas
(_siladhara_). O aumento de pessoas interessadas em viver a vida
monástica, ou interessadas em a apoiar, tornou possível abrir outros
mosteiros em Inglaterra e em outros países; ajudou também a estabelecer
em 1984 um grande centro de treino, Amarāvatī Buddhist Monastery.

Amarāvatī situa-se nas imediações da vila de Great Gaddesden perto de
Hemel Hempstead em Hertfordshire. Funciona simultaneamente como mosteiro
e centro de retiros acolhendo aqueles que estão interessados nos
ensinamentos do Buddha. Está aberto para receber hóspedes que estejam
interessados em ajudar, praticar os preceitos e desenvolver a meditação.
